//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by InternProject1.rc
//
#define IDD_INTERNPROJECT1_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDD_MANAGESTUDENTS              132
#define IDD_MANAGE_PEOPLE               132
#define IDD_ALL_STUDENTS                136
#define IDD_ALL_STUDENTS_DLG            136
#define IDD_MANAGE_SUBJECTS_DIALOG      140
#define IDD_ALL_SUBJECTS                144
#define IDD_ALL_SUBJECTS_DLG            144
#define IDD_MANAGE_GRADES               152
#define IDD_STUDENT_COMBINED            158
#define IDD_TEACHER_COMBINED            160
#define IDD_GRADES_COMBINED             162
#define IDD_ALL_GRADES_DLG              164
#define IDD_SUBJECT_COMBINED            166
#define IDD_STUDENT_AVERAGE_GRADE       168
#define IDD_EXCELLENT_STUDENTS          170
#define IDD_FAILS                       172
#define IDD_BIRTHDAYERS                 174
#define IDD_BIRTHDAYERS_DLG             174
#define IDD_SCHEDULE                    176
#define IDD_EDIT_SCHEDULE               178
#define IDD_COMBINED_SCHEDULED_CLASS    180
#define IDD_COMBINED_SCHEDULED_CLASS_DLG 180
#define IDR_SUBJECT                     182
#define IDD_ALL_TEACHERS_DLG            183
#define IDD_NEW_CLASS                   185
#define IDD_COMBINED_STUDENT_CLASS      185
#define IDD_ALL_STUDENT_CLASSES         189
#define IDR_TOOLBAR_MENU                193
#define IDC_EDIT1                       1000
#define IDC_TEACHER_ID_EDIT             1000
#define IDC_EDIT_NEW_CLASS_NAME         1000
#define IDC_EDIT_COMBINED_CLASS_NAME    1000
#define IDC_SCHOOL_AVERAGE_EDIT         1000
#define IDC_DATETIMEPICKER1             1001
#define IDC_DATETIMEPICKER              1001
#define IDC_ALL_STUDENTS                1002
#define IDC_BUTTON5                     1006
#define IDC_BUTTON6                     1007
#define IDC_BUTTON7                     1008
#define IDC_BUTTON2                     1009
#define IDC_BUTTON3                     1010
#define IDC_BUTTON4                     1011
#define IDC_BTN_EDIT_SCHEDULE_REMOVE    1011
#define IDC_BTN_ADD_NEW_CLASS           1011
#define IDC_BTN_MANAGE_STUDENT_CLASSES  1011
#define IDC_MANAGESTUDENTS              1012
#define IDC_COMBO1                      1013
#define IDC_SUBJECT_TEACHER_COMBO       1013
#define IDC_COMBO_NEW_CLASS_TEACHERS    1013
#define IDC_COMBO_COMBINED_CLASS_TEACHERS 1013
#define IDC_LIST2                       1016
#define IDC_BUTTON1                     1017
#define IDC_LIST1                       1018
#define IDC_EDIT2                       1019
#define IDC_TEACHER_FIRST_NAME_EDIT     1019
#define IDC_COMBO2                      1020
#define IDD_STUDENT_AVERAGE_GRADE_SUBJECT_COMBO 1020
#define IDC_RADIO4                      1024
#define IDC_RADIO5                      1025
#define IDC_COMBO3                      1032
#define IDC_GRADES_GRADE_COMBO          1032
#define IDC_EDIT3                       1034
#define IDC_TEACHER_LAST_NAME_EDIT      1034
#define IDC_GRADES_STUDENT_COMBO        1037
#define IDC_GRADE_DATETIMEPICKER1       1038
#define IDC_GRADE_DATETIMEPICKER        1038
#define IDC_GRADES_LIST                 1039
#define IDC_GRADES_LIST1                1039
#define IDC_COMBO_CLASSES               1040
#define IDC_EDIT4                       1041
#define IDC_STUDENT_NUMBER_IN_CLASS_EDIT 1041
#define IDC_TEACHERS_LIST               1043
#define IDC_BTN_TEACHERS_ADD            1044
#define IDC_BTN_TEACHERS_EDIT           1045
#define IDC_BTN_TEACHERS_REMOVE         1046
#define IDC_BTN_GRADES_ADD              1047
#define IDC_BTN_GRADES_EDIT             1048
#define IDC_BTN_GRADES_REMOVE           1049
#define IDC_BTN_STUDENTS_ADD            1050
#define IDC_BTN_STUDENTS_EDIT           1051
#define IDC_BTN_STUDENTS_REMOVE         1052
#define IDC_SUBJECTS_LIST               1053
#define IDC_BTN_SUBJECTS_ADD            1054
#define IDC_BTN_SUBJECTS_EDIT           1055
#define IDC_BTN_SUBJECTS_REMOVE         1056
#define IDD_COMBINED_SCHEDULED_CLASS_COMBO 1057
#define IDC_BTN_EDIT_SCHEDULE_ADD       1058
#define IDC_BTN_EDIT_SCHEDULE_UP        1059
#define IDC_BTN_EDIT_SCHEDULE_DOWN      1060
#define IDC_EDIT_SCHEDULE_LIST          1061
#define IDC_EDIT_SCHEDULE_COMBO         1062
#define IDC_EDIT_SCHEDULE_EDIT          1063
#define IDC_EXCELLENT_STUDENTS_LIST     1064
#define IDC_RETAKE_LIST                 1065
#define IDC_BAD_GRADES_LIST             1066
#define IDC_GRADES_GRADE_ID             1067
#define IDC_GRADES_SUBJECT_COMBO        1068
#define IDC_BTN_ALL_GRADES              1069
#define IDC_BTN_ADD_GRADES              1070
#define IDC_BTN_ALL_SUBJECTS            1071
#define IDC_BTN_ADD_SUBJECT             1072
#define IDC_SCHEDULE_LIST               1073
#define IDC_SCHEDULE_CLASS_COMBO        1074
#define IDC_BTN_SCHEDULE_EDIT           1075
#define IDD_STUDENT_AVERAGE_GRADE_STUDENT_COMBO 1076
#define IDD_STUDENT_AVERAGE_GRADE_STUDENT_EDIT 1077
#define IDD_STUDENT_AVERAGE_GRADE_SUBJECT_EDIT 1078
#define IDC_STUDENT_ID                  1079
#define IDC_STUDENT_FIRST_NAME_EDIT     1080
#define IDC_STUDENT_FIRST_NAME_STATIC   1081
#define IDC_STUDENT_LAST_NAME_STATIC    1082
#define IDC_STUDENT_NUMBER_IN_CLASS_STATIC 1083
#define IDC_STUDENT_BIRTHDAY_STATIC     1084
#define IDC_STUDENT_LAST_NAME_EDIT      1085
#define IDC_SUBJECT_ID_EDIT             1086
#define IDC_SUBJECT_ID_STATIC           1087
#define IDC_SUBJECT_NAME_STATIC         1088
#define IDC_SUBJECT_NAME_EDIT           1089
#define IDC_SUBJECT_TEACHER_STATIC      1090
#define IDC_SUBJECT_ROOM_STATIC         1091
#define IDC_SUBJECT_ROOM_EDIT           1092
#define IDC_TEACHER_ID_STATIC           1093
#define IDC_TEACHER_FIRST_NAME_STATIC   1094
#define IDC_TEACHER_LAST_NAME_STATIC    1095
#define IDC_BTN_ADD_STUDENT_CLASS       1100
#define IDC_BTN_EDIT_STUDENT_CLASS      1101
#define IDC_BTN_REMOVE_STUDENT_CLASS    1102
#define IDC_ALL_STUDENT_CLASSES_LIST    1103
#define IDC_STUDENTS_LIST               1105
#define IDC_CLASSES_LIST                1106
#define ID_ADD_EDIT                     32771
#define ID_ADD_DELETE                   32772
#define ID_ADD_VIEW                     32773
#define ID_POPUP_ADD                    32774
#define ID_POPUP_EDIT                   32775
#define ID_POPUP_DELETE                 32776
#define ID_POPUP_VIEW                   32777
#define ID_STUDENTS_VIEWALL             32778
#define ID_STUDENTS_ADDNEW              32779
#define ID_STUDENTS_EXCELLENTS          32780
#define ID_STUDENTS_AVERAGE             32781
#define ID_STUDENTS_FAILS               32782
#define ID_STUDENTS_BIRTHDAYERS         32783
#define ID_TEACHERS_VIEWALL             32784
#define ID_TEACHERS_ADDNEW              32785
#define ID_CLASSES_VIEWALL              32786
#define ID_CLASSES_ADDNEW               32787
#define ID_SUBJECTS                     32788
#define ID_SUBJECTS_VIEWALL             32789
#define ID_SUBJECTS_ADDNEW              32790
#define ID_GRADES                       32791
#define ID_GRADES_VIEWALL               32792
#define ID_GRADES_ADDNEW                32793
#define ID_SCHEDULE                     32794
#define ID_SCHEDULE_VIEW                32795

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        194
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1109
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
